/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MinigamesRouteImport } from './routes/minigames'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MinigamesGameRouteImport } from './routes/minigames.$game'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MinigamesRoute = MinigamesRouteImport.update({
  id: '/minigames',
  path: '/minigames',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinigamesGameRoute = MinigamesGameRouteImport.update({
  id: '/$game',
  path: '/$game',
  getParentRoute: () => MinigamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/friends': typeof FriendsRoute
  '/history': typeof HistoryRoute
  '/minigames': typeof MinigamesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/training': typeof TrainingRoute
  '/minigames/$game': typeof MinigamesGameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/friends': typeof FriendsRoute
  '/history': typeof HistoryRoute
  '/minigames': typeof MinigamesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/training': typeof TrainingRoute
  '/minigames/$game': typeof MinigamesGameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/friends': typeof FriendsRoute
  '/history': typeof HistoryRoute
  '/minigames': typeof MinigamesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/training': typeof TrainingRoute
  '/minigames/$game': typeof MinigamesGameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/friends'
    | '/history'
    | '/minigames'
    | '/profile'
    | '/training'
    | '/minigames/$game'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/friends'
    | '/history'
    | '/minigames'
    | '/profile'
    | '/training'
    | '/minigames/$game'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/friends'
    | '/history'
    | '/minigames'
    | '/profile'
    | '/training'
    | '/minigames/$game'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FriendsRoute: typeof FriendsRoute
  HistoryRoute: typeof HistoryRoute
  MinigamesRoute: typeof MinigamesRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  TrainingRoute: typeof TrainingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minigames': {
      id: '/minigames'
      path: '/minigames'
      fullPath: '/minigames'
      preLoaderRoute: typeof MinigamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minigames/$game': {
      id: '/minigames/$game'
      path: '/$game'
      fullPath: '/minigames/$game'
      preLoaderRoute: typeof MinigamesGameRouteImport
      parentRoute: typeof MinigamesRoute
    }
  }
}

interface MinigamesRouteChildren {
  MinigamesGameRoute: typeof MinigamesGameRoute
}

const MinigamesRouteChildren: MinigamesRouteChildren = {
  MinigamesGameRoute: MinigamesGameRoute,
}

const MinigamesRouteWithChildren = MinigamesRoute._addFileChildren(
  MinigamesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FriendsRoute: FriendsRoute,
  HistoryRoute: HistoryRoute,
  MinigamesRoute: MinigamesRouteWithChildren,
  ProfileRoute: ProfileRoute,
  TrainingRoute: TrainingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
